# Generated by Django 4.2.2 on 2023-06-26 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0002_rename_email_user_senha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=200)),
                ('nome', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Site.user')),
            ],
        ),
    ]
